// Date: 9-12-2013 16:57:29
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package net.ivorius.plantmod.client;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPlantOre extends ModelBase
{
	//fields
	ModelRenderer plantbase1;
	ModelRenderer plantbase2;
	ModelRenderer leaf1;
	ModelRenderer leaf1b;
	ModelRenderer leaf2;
	ModelRenderer leaf2b;
	ModelRenderer leaf3;
	ModelRenderer leaf3b;
	ModelRenderer leaf4;
	ModelRenderer leaf4b;
	ModelRenderer leaf5;
	ModelRenderer leaf5b;
	ModelRenderer leaf6;
	ModelRenderer leaf6b;
	ModelRenderer leaf7;
	ModelRenderer leaf7b;
	ModelRenderer leaf8;
	ModelRenderer leaf8b;
	ModelRenderer root1;
	ModelRenderer root2;
	ModelRenderer root3;
	ModelRenderer root4;
	ModelRenderer fruit1;
	ModelRenderer fruit2;
	ModelRenderer fruit3;

	public ModelPlantOre()
	{
		textureWidth = 512;
		textureHeight = 256;

		plantbase1 = new ModelRenderer(this, 58, -28);
		plantbase1.addBox(0F, -22F, -14F, 0, 250, 28);
		plantbase1.setRotationPoint(0F, 24F, 0F);
		plantbase1.setTextureSize(512, 256);
		plantbase1.mirror = true;
		setRotation(plantbase1, 0F, 0F, 0F);
		plantbase2 = new ModelRenderer(this, 0, 0);
		plantbase2.addBox(-14F, -22F, 0F, 28, 250, 0);
		plantbase2.setRotationPoint(0F, 24F, 0F);
		plantbase2.setTextureSize(512, 256);
		plantbase2.mirror = true;
		setRotation(plantbase2, 0F, 0F, 0F);
		leaf1 = new ModelRenderer(this, 120, 0);
		leaf1.addBox(-8F, 0F, -7F, 8, 0, 14);
		leaf1.setRotationPoint(7.5F, 12F, 0F);
		leaf1.setTextureSize(512, 256);
		leaf1.mirror = true;
		setRotation(leaf1, 0F, 0F, -0.3346075F);
		leaf1b = new ModelRenderer(this, 120, 16);
		leaf1b.addBox(0F, 0F, -7F, 10, 0, 14);
		leaf1b.setRotationPoint(7.5F, 12F, 0F);
		leaf1b.setTextureSize(512, 256);
		leaf1b.mirror = true;
		setRotation(leaf1b, 0F, 0F, 0.4461433F);
		leaf2 = new ModelRenderer(this, 120, 34);
		leaf2.addBox(0F, 0F, -7F, 8, 0, 14);
		leaf2.setRotationPoint(-7.5F, 11F, 0F);
		leaf2.setTextureSize(512, 256);
		leaf2.mirror = true;
		setRotation(leaf2, 0F, 0F, 0.3346145F);
		leaf2b = new ModelRenderer(this, 120, 50);
		leaf2b.addBox(-9F, 0F, -7F, 9, 0, 14);
		leaf2b.setRotationPoint(-7.5F, 11F, 0F);
		leaf2b.setTextureSize(512, 256);
		leaf2b.mirror = true;
		setRotation(leaf2b, 0F, 0F, -0.7063936F);
		leaf3 = new ModelRenderer(this, 120, 68);
		leaf3.addBox(-7F, 0F, -8F, 14, 0, 8);
		leaf3.setRotationPoint(0F, 14F, 7.5F);
		leaf3.setTextureSize(512, 256);
		leaf3.mirror = true;
		setRotation(leaf3, 0.3346145F, 0F, 0F);
		leaf3b = new ModelRenderer(this, 120, 80);
		leaf3b.addBox(-7F, 0F, 0F, 14, 0, 8);
		leaf3b.setRotationPoint(0F, 14F, 7.5F);
		leaf3b.setTextureSize(512, 256);
		leaf3b.mirror = true;
		setRotation(leaf3b, -0.3346075F, 0F, 0F);
		leaf4 = new ModelRenderer(this, 120, 92);
		leaf4.addBox(-7F, 0F, 0F, 14, 0, 8);
		leaf4.setRotationPoint(0F, 10F, -7.5F);
		leaf4.setTextureSize(512, 256);
		leaf4.mirror = true;
		setRotation(leaf4, -0.3346145F, 0F, 0F);
		leaf4b = new ModelRenderer(this, 120, 104);
		leaf4b.addBox(-7F, 0F, -10F, 14, 0, 10);
		leaf4b.setRotationPoint(0F, 10F, -7.5F);
		leaf4b.setTextureSize(512, 256);
		leaf4b.mirror = true;
		setRotation(leaf4b, 1.07818F, 0F, 0F);
		leaf5 = new ModelRenderer(this, 180, 0);
		leaf5.addBox(-10F, 0F, -10F, 20, 0, 10);
		leaf5.setRotationPoint(0F, 1F, 9.8F);
		leaf5.setTextureSize(512, 256);
		leaf5.mirror = true;
		setRotation(leaf5, 0.1858931F, 0F, 0F);
		leaf5b = new ModelRenderer(this, 180, 14);
		leaf5b.addBox(-10F, 0F, 0F, 20, 0, 14);
		leaf5b.setRotationPoint(0F, 1F, 9.8F);
		leaf5b.setTextureSize(512, 256);
		leaf5b.mirror = true;
		setRotation(leaf5b, -0.3346075F, 0F, 0F);
		leaf6 = new ModelRenderer(this, 180, 31);
		leaf6.addBox(-10F, 0F, 0F, 20, 0, 9);
		leaf6.setRotationPoint(0F, 0F, -8.8F);
		leaf6.setTextureSize(512, 256);
		leaf6.mirror = true;
		setRotation(leaf6, -0.2230736F, 0F, 0F);
		leaf6b = new ModelRenderer(this, 180, 44);
		leaf6b.addBox(-10F, 0F, -14F, 20, 0, 14);
		leaf6b.setRotationPoint(0F, 0F, -8.8F);
		leaf6b.setTextureSize(512, 256);
		leaf6b.mirror = true;
		setRotation(leaf6b, 0.669215F, 0F, 0F);
		leaf7 = new ModelRenderer(this, 180, 62);
		leaf7.addBox(-12F, 0F, -10F, 12, 0, 20);
		leaf7.setRotationPoint(11.8F, 1F, 0F);
		leaf7.setTextureSize(512, 256);
		leaf7.mirror = true;
		setRotation(leaf7, 0F, 0F, -0.185895F);
		leaf7b = new ModelRenderer(this, 180, 84);
		leaf7b.addBox(0F, 0F, -10F, 11, 0, 20);
		leaf7b.setRotationPoint(11.8F, 1F, 0F);
		leaf7b.setTextureSize(512, 256);
		leaf7b.mirror = true;
		setRotation(leaf7b, 0F, 0F, 0.8922867F);
		leaf8 = new ModelRenderer(this, 180, 106);
		leaf8.addBox(0F, 0F, -10F, 12, 0, 20);
		leaf8.setRotationPoint(-11.8F, 0F, 0F);
		leaf8.setTextureSize(512, 256);
		leaf8.mirror = true;
		setRotation(leaf8, 0F, 0F, 0.185895F);
		leaf8b = new ModelRenderer(this, 180, 128);
		leaf8b.addBox(-11F, 0F, -10F, 11, 0, 20);
		leaf8b.setRotationPoint(-11.8F, 0F, 0F);
		leaf8b.setTextureSize(512, 256);
		leaf8b.mirror = true;
		setRotation(leaf8b, 0F, 0F, -0.3717861F);
		root1 = new ModelRenderer(this, 260, 0);
		root1.addBox(-7F, 0F, 0F, 14, 160, 0);
		root1.setRotationPoint(0F, 24F, 0F);
		root1.setTextureSize(512, 256);
		root1.mirror = true;
		setRotation(root1, 0.0371786F, 0F, 0F);
		root2 = new ModelRenderer(this, 290, 0);
		root2.addBox(-11F, 0F, 0F, 22, 130, 0);
		root2.setRotationPoint(0F, 24F, 0F);
		root2.setTextureSize(512, 256);
		root2.mirror = true;
		setRotation(root2, -0.0743572F, 0F, 0F);
		root3 = new ModelRenderer(this, 336, 0);
		root3.addBox(0F, 0F, -9F, 0, 200, 20);
		root3.setRotationPoint(0F, 24F, 0F);
		root3.setTextureSize(512, 256);
		root3.mirror = true;
		setRotation(root3, 0F, 0F, 0.0743572F);
		root4 = new ModelRenderer(this, 378, 0);
		root4.addBox(0F, 0F, -9F, 0, 180, 18);
		root4.setRotationPoint(0F, 24F, 0F);
		root4.setTextureSize(512, 256);
		root4.mirror = true;
		setRotation(root4, 0F, 0F, -0.0371786F);
		fruit1 = new ModelRenderer(this, 120, 120);
		fruit1.addBox(-1F, 0F, -1F, 3, 3, 3);
		fruit1.setRotationPoint(1F, 3F, -3F);
		fruit1.setTextureSize(512, 256);
		fruit1.mirror = true;
		setRotation(fruit1, -0.1115358F, 0.1858931F, -0.1487144F);
		fruit2 = new ModelRenderer(this, 120, 128);
		fruit2.addBox(-3F, 0F, -3F, 6, 6, 6);
		fruit2.setRotationPoint(-1F, 7F, 2F);
		fruit2.setTextureSize(512, 256);
		fruit2.mirror = true;
		setRotation(fruit2, 0.3346075F, -0.2230717F, 0.2602503F);
		fruit3 = new ModelRenderer(this, 120, 142);
		fruit3.addBox(-4F, 0F, -4F, 4, 4, 4);
		fruit3.setRotationPoint(0F, 13F, 0F);
		fruit3.setTextureSize(512, 256);
		fruit3.mirror = true;
		setRotation(fruit3, -0.1858931F, 0.1858931F, 0F);
	}

	public void render( Entity entity, float f, float f1, float f2, float f3, float f4, float f5 )
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		plantbase1.render(f5);
		plantbase2.render(f5);
		leaf1.render(f5);
		leaf1b.render(f5);
		leaf2.render(f5);
		leaf2b.render(f5);
		leaf3.render(f5);
		leaf3b.render(f5);
		leaf4.render(f5);
		leaf4b.render(f5);
		leaf5.render(f5);
		leaf5b.render(f5);
		leaf6.render(f5);
		leaf6b.render(f5);
		leaf7.render(f5);
		leaf7b.render(f5);
		leaf8.render(f5);
		leaf8b.render(f5);
		root1.render(f5);
		root2.render(f5);
		root3.render(f5);
		root4.render(f5);
		fruit1.render(f5);
		fruit2.render(f5);
		fruit3.render(f5);
	}

	private void setRotation( ModelRenderer model, float x, float y, float z )
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}
