// Date: 31-3-2014 11:48:26
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package net.ivorius.plantmod.client;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelInstablePlant extends ModelBase
{
	public boolean renderCull;
	
	//fields
	ModelRenderer leafbase;
	ModelRenderer leaf1;
	ModelRenderer leaf2;
	ModelRenderer leaf3;
	ModelRenderer leaf4;
	ModelRenderer flower1;
	ModelRenderer flower2;
	ModelRenderer stamper;

	public ModelInstablePlant()
	{
		textureWidth = 128;
		textureHeight = 64;

		leafbase = new ModelRenderer(this, 0, 0);
		leafbase.addBox(-8F, 0F, -8F, 16, 0, 16);
		leafbase.setRotationPoint(0F, 23.99F, 0F);
		leafbase.setTextureSize(128, 64);
		leafbase.mirror = true;
		setRotation(leafbase, 0F, 0F, 0F);
		leaf1 = new ModelRenderer(this, 0, 17);
		leaf1.addBox(-8F, 0F, 0F, 16, 0, 9);
		leaf1.setRotationPoint(0F, 24F, 0F);
		leaf1.setTextureSize(128, 64);
		leaf1.mirror = true;
		setRotation(leaf1, 0.3346075F, 0F, 0F);
		leaf2 = new ModelRenderer(this, 0, 27);
		leaf2.addBox(-8F, 0F, 0F, 16, 0, 9);
		leaf2.setRotationPoint(0F, 24F, 0F);
		leaf2.setTextureSize(128, 64);
		leaf2.mirror = true;
		setRotation(leaf2, 0.2230717F, 1.570796F, 0F);
		leaf3 = new ModelRenderer(this, 0, 37);
		leaf3.addBox(-8F, 0F, 0F, 16, 0, 9);
		leaf3.setRotationPoint(0F, 24F, 0F);
		leaf3.setTextureSize(128, 64);
		leaf3.mirror = true;
		setRotation(leaf3, 0.3126102F, 3.141593F, 0F);
		leaf4 = new ModelRenderer(this, 0, 47);
		leaf4.addBox(-8F, 0F, 0F, 16, 0, 9);
		leaf4.setRotationPoint(0F, 24F, 0F);
		leaf4.setTextureSize(128, 64);
		leaf4.mirror = true;
		setRotation(leaf4, 0.2602503F, -1.570796F, 0F);
		flower1 = new ModelRenderer(this, 65, 0);
		flower1.addBox(-4F, -8F, 0F, 8, 8, 4);
		flower1.setRotationPoint(0F, 24F, 0F);
		flower1.setTextureSize(128, 64);
		flower1.mirror = true;
		setRotation(flower1, -0.1487144F, 0.7853982F, 0F);
		flower2 = new ModelRenderer(this, 65, 13);
		flower2.addBox(-4F, -8F, -4F, 8, 8, 4);
		flower2.setRotationPoint(0F, 24F, 0F);
		flower2.setTextureSize(128, 64);
		flower2.mirror = true;
		setRotation(flower2, 0.1487195F, 0.7853982F, 0F);
		stamper = new ModelRenderer(this, 65, 26);
		stamper.addBox(-1.5F, -3F, -1.5F, 3, 3, 3);
		stamper.setRotationPoint(0F, 24F, 0F);
		stamper.setTextureSize(128, 64);
		stamper.mirror = true;
		setRotation(stamper, 0F, 0F, 0F);
	}

	public void render( Entity entity, float f, float f1, float f2, float f3, float f4, float f5 )
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		
		if (renderCull)
		{
			leafbase.render(f5);
			leaf1.render(f5);
			leaf2.render(f5);
			leaf3.render(f5);
			leaf4.render(f5);			
			stamper.render(f5);
		}
		else
		{
			flower1.render(f5);
			flower2.render(f5);			
		}
	}

	private void setRotation( ModelRenderer model, float x, float y, float z )
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
	
	@Override
	public void setRotationAngles( float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity )
	{
		super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
		
		float mouthOpen = (MathHelper.sin(par2 * 1.3f) + 0.9f) * 0.3f * Math.min(par1 * 1.6f, 1.0f);
//		flower1.rotateAngleZ = mouthOpen;
//		flower1.rotateAngleX = mouthOpen;
//		flower2.rotateAngleZ = -mouthOpen;
//		flower2.rotateAngleX = -mouthOpen;
		// Looks like munching

		flower1.rotateAngleX = -mouthOpen;
		flower2.rotateAngleX = mouthOpen;
}
}
