// Date: 28-4-2014 13:36:01
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package net.ivorius.plantmod.client;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPlantHealth extends ModelBase
{
	public boolean renderCull;
	
	//fields
	ModelRenderer stem1;
	ModelRenderer stem2;
	ModelRenderer stem3;
	ModelRenderer stem4;
	ModelRenderer leaftop;
	ModelRenderer leafmiddle;
	ModelRenderer leafbottom;
	ModelRenderer powerflower;

	public ModelPlantHealth()
	{
		textureWidth = 128;
		textureHeight = 64;

		stem1 = new ModelRenderer(this, 0, 0);
		stem1.addBox(-8F, 0F, 0F, 16, 16, 0);
		stem1.setRotationPoint(0F, 8F, 0F);
		stem1.setTextureSize(128, 64);
		stem1.mirror = true;
		setRotation(stem1, 0F, 0F, 0F);
		stem2 = new ModelRenderer(this, 0, 0);
		stem2.addBox(0F, 0F, -8F, 0, 16, 16);
		stem2.setRotationPoint(0F, 8F, 0F);
		stem2.setTextureSize(128, 64);
		stem2.mirror = true;
		setRotation(stem2, 0F, 0F, 0F);
		stem3 = new ModelRenderer(this, 0, 32);
		stem3.addBox(-8F, 0F, 0F, 16, 16, 0);
		stem3.setRotationPoint(0F, 8F, 0F);
		stem3.setTextureSize(128, 64);
		stem3.mirror = true;
		setRotation(stem3, 0F, 0.7853982F, 0F);
		stem4 = new ModelRenderer(this, 0, 32);
		stem4.addBox(0F, 0F, -8F, 0, 16, 16);
		stem4.setRotationPoint(0F, 8F, 0F);
		stem4.setTextureSize(128, 64);
		stem4.mirror = true;
		setRotation(stem4, 0F, 0.7853982F, 0F);
		leaftop = new ModelRenderer(this, 30, 0);
		leaftop.addBox(-8F, 0F, -8F, 16, 0, 16);
		leaftop.setRotationPoint(0F, 8F, 0F);
		leaftop.setTextureSize(128, 64);
		leaftop.mirror = true;
		setRotation(leaftop, 0F, 0F, 0F);
		leafmiddle = new ModelRenderer(this, 40, 17);
		leafmiddle.addBox(-5F, 4.7F, 1.5F, 6, 0, 6);
		leafmiddle.setRotationPoint(0F, 8F, 0F);
		leafmiddle.setTextureSize(128, 64);
		leafmiddle.mirror = true;
		setRotation(leafmiddle, -0.0743572F, 0.3346075F, 0F);
		leafbottom = new ModelRenderer(this, 38, 24);
		leafbottom.addBox(0F, 8.9F, -6F, 8, 0, 8);
		leafbottom.setRotationPoint(0F, 8F, 0F);
		leafbottom.setTextureSize(128, 64);
		leafbottom.mirror = true;
		setRotation(leafbottom, 0.0743572F, 0.4089647F, 0F);
		powerflower = new ModelRenderer(this, 40, 35);
		powerflower.addBox(-2.5F, -4.01F, -2.5F, 5, 4, 5);
		powerflower.setRotationPoint(0F, 8F, 0F);
		powerflower.setTextureSize(128, 64);
		powerflower.mirror = true;
		setRotation(powerflower, 0F, 0F, 0F);
	}

	public void render( Entity entity, float f, float f1, float f2, float f3, float f4, float f5 )
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		
		if (renderCull)
		{
			stem1.render(f5);
			stem2.render(f5);
			stem3.render(f5);
			stem4.render(f5);
			leaftop.render(f5);
			leafmiddle.render(f5);
			leafbottom.render(f5);			
		}
		else
			powerflower.render(f5);
	}

	private void setRotation( ModelRenderer model, float x, float y, float z )
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}
